###
GET http://localhost:3000/person


###
GET http://localhost:3000/auth/google

###
GET http://localhost:3000/events

###
GET http://localhost:3000/person/6415278a36a84d3235f6c15d

 
###
PUT http://localhost:3000/person/6415278a36a84d3235f6c15d HTTP/1.1
Content-Type: application/json

{
    "firstName":"Denise",
    "lastName":"Rebollo",
    "email":"drebollo116@gmail.com",
    "birthday":"03/25/1984",
    "city": "Albuquerque",
    "state": "New Mexico"
}

###
DELETE http://localhost:3000/person/123456789132465468 HTTP/1.1

