###
GET http://localhost:3000/person

###
GET http://localhost:3000/person/6415278a36a84d3235f6c15d

//DO NOT NEED _ 
###
POST http://localhost:3000/person HTTP/1.1
Content-Type: application/json

{
    "firstName":"Denise",
    "lastName":"Rebollo",
    "email":"drebollo116@gmail.com",
    "birthday":"03/26/1984",
    "city": "Albuquerque",
    "state": "NM"
}

###
PUT http://localhost:3000/person/6415278a36a84d3235f6c15d HTTP/1.1
Content-Type: application/json

{
    "firstName":"Denise",
    "lastName":"Rebollo",
    "email":"drebollo116@gmail.com",
    "birthday":"March 25",
    "city": "Albuquerque",
    "state": "New Mexico"
}

###
DELETE http://localhost:3000/person/6418f2112a3036a10ea9d8b9 HTTP/1.1

