###
GET http://localhost:3000/person

###
GET http://localhost:3000/person/640eb27191597d1e20d9ed29

###
POST http://localhost:3000/person HTTP/1.1
Content-Type: application/json

{
    "firstName":"Alfredo",
    "lastName":"Rebollo",
    "email":"user@gmail.com",
    "birthDate":"06/15/1999",
    "City": "Albuquerque",
    "State": "NM"
}

###
DELETE http://localhost:3000/person/ HTTP/1.1

